### ISSUE TITLE
Not freely available

### ISSUE THREAD

**Issue by ncfavier** [snowleopard/alga-paper#1]
README.md claims the paper is freely available from ACM. This is not the case, ACM is asking me to log in via my institution to get access.

**Comment by snowleopard** [comment]
I've just clicked through the README link and got the PDF from ACM, no questions asked.

Note: you must use the README link -- simply searching the paper on the ACM website won't work. 

If the ACM link is not working for you for some reason, just use the preprint linked below. It's the same.

**Comment by ncfavier** [comment]
I did use the README link. It looks like the free access might be dependent on location? It seems to be available in North America but not in Europe.

**Comment by snowleopard** [comment]
I'm in Europe, so some other theory is needed.

(I'm joking really; reverse-engineering bugs in ACM Digital Library doesn't sound like fun.)
